spring.application.name=springai
server.port=8080

# SQLite Database
spring.datasource.url=jdbc:sqlite:springai.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false